allure.clean.start=true
allure.report.remove.attachments=true
allure.results.directory=target/allure-results
allure.report.directory=target/allure-report


#allure.report.viewer=target/allure-report
#allure.report.viewer.open=false
#allure.report.viewer.port=9090